{
 "title": "Environmental sensors",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "eCO₂",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "yaxes": [
    { "format": "ppm" }
   ],
   "targets": [
    {
     "expr": "sgp30_co2_ppm{job='enviro-sensors',instance='lounge'}"
    }
   ]
  },
  {
   "title": "TVOC",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "conppb" } },
   "yaxes": [
    { "format": "conppb" }
   ],
   "targets": [
    {
     "expr": "sgp30_tvoc_ppb{job='enviro-sensors',instance='lounge'}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "bme280_temperature_celsius{job='enviro-sensors',instance='lounge'}"
    }
   ]
  },
  {
   "title": "Relative Humidity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "expr": "bme280_humidity_ratio{job='enviro-sensors',instance='lounge'} * 100"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "yaxes": [
    { "format": "pressurepa" }
   ],
   "targets": [
    {
     "expr": "bme280_pressure_pascals{job='enviro-sensors',instance='lounge'}"
    }
   ]
  }
 ]
}